### ISSUE TITLE
fyi.. confused on why this change keeps repeating for 2.1.2

### ISSUE THREAD

**Issue by SteveDevOps** [evenup/evenup-curator#27]
This is repeating now for every run to every node using curator..

notice	ensure changed '2.1.1' to '2.1.2'	/Stage[main]/Curator/Package[elasticsearch-curator]/ensure	/etc/puppetlabs/puppet/environments/dev/modules/curator/manifests/init.pp	66	2015-02-13 07:36 EST

I would've expected a one time occurrence.. I know you guys staged new version number in commit? Just confused on why this keeps coming up as new change.

**Comment by jlambert121** [comment]
What provider are you using?

**Comment by SteveDevOps** [comment]
I am on centos 6.6, pip provider, EPEL repo, and curator was installed by puppet enterprise 3.7.1 as 

 ~]# curator --version
curator 2.1.1

**Comment by jlambert121** [comment]
It doesn't look like this is the same as #24, but it does seem to be more a pip issue than this module's issue since all the module does is set the version but it doesn't appear the provider is actually making that version a reality.  If you run puppet agent with --debug does it give any insight about an error occurring with the upgrade of the package?

**Comment by SteveDevOps** [comment]
No, no debug output occurs for curator, pip, or python.

**Comment by jlambert121** [comment]
That is very odd.  If you run the pip command in the debug output does it correctly update?

**Comment by SteveDevOps** [comment]
pip not showing up in debug output.. ran a puppet --debug on one of my nodes employing the curator module.. also ran puppet parser validate against my manifest.. all clean.

**Comment by SteveDevOps** [comment]
here's actual run output:
```
 puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for evest-devsearch-01.evestment.local
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type/package.rb:430:in `block (3 levels) in <module:Puppet>')
Info: Applying configuration version '1424375031'
Notice: /Stage[main]/Curator/Package[elasticsearch-curator]/ensure: ensure changed '2.1.1' to '2.1.2'
Notice: Finished catalog run in 4.50 seconds
```
