### ISSUE TITLE
stuck on 2.1.1

### ISSUE THREAD

**Issue by SteveDevOps** [evenup/evenup-curator#39]
on puppet agent run I get a 

Notice: /Stage[main]/Curator/Package[elasticsearch-curator]/ensure: ensure changed '2.1.1' to '3.0.3'

but it doesn't actually perform the upgrade. curator --version gives me a 2.1.1
if I manually try to uninstall / reinstall through pip, I end up with 2.1.1.

I'm on python 2.6.6
puppet enterprise 3.7.2
centos 6.6
pip 1.3.1
ES 1.4.2

My manifest is not specifying version so by default, it's trying to upgrade to 3.0.3. I've had this work on other machines and I can't find what's different. 

I have tried to have manifest do the uninstall, reinstall by toggling ensure => 'absent' -- and I still end up with 2.1.1.

I tried direct download of package -- If I manually surf to pip repo, download the .tgz and try to run setup.py I get a command import not found. I have setuptools installed. I've tried everything I know to try.

I'm running different puppet environments and made sure to upgrade curator module first. Stuck. Help.

**Comment by SteveDevOps** [comment]
ok finally got manual install to work but never understood why puppet couldn't handle via module.
I went to: https://pypi.python.org/pypi/elasticsearch-curator and and got link for tar.gz
.. ran a wget https://pypi.python.org/packages/source/e/elasticsearch-curator/elasticsearch-curator-3.0.3.tar.gz

then realized I didn't need to extract -- I'm new to pip and python --  and ran pip install elasticsearch-curator/elasticsearch-curator-3.0.3.tar.gz

walah, now on 3.0.3 and puppet now understands I'm on 3.0.3 -- no longer receive ensure message.

**Comment by jlambert121** [comment]
I believe this is something with the puppet pip provider rather than this module.  I think starting with the PL guys would be the best place to start.
