### ISSUE TITLE
Delete snapshots requires --repository

### ISSUE THREAD

**Issue by abo-adapt** [evenup/evenup-curator#43]
The curator::job class does not define "delete snapshots" correctly. It needs to know which repository to delete snaphots from.

Here is a patch that fixes it:

```
diff --git a/modules/curator/manifests/job.pp b/modules/curator/manifests/job.pp
index 0069ada..7e4cd57 100644
--- a/modules/curator/manifests/job.pp
+++ b/modules/curator/manifests/job.pp
@@ -188,8 +188,16 @@ define curator::job (
       } else {
         $_ds = ''
       }
+      if $repository {
+        if !is_string($repository) {
+        } else {
+          $_repo = " --repository ${repository}"
+        }
+      } else {
+        $_repo = ''
+      }

-      $exec = "delete${_ds} ${sub_command}"
+      $exec = "delete${_ds} ${sub_command}${_repo}"
     }
     'optimize': {
       # optimize validations

```

**Comment by jlambert121** [comment]
Sorry for the delay on this.  I was just looking at incorporating it and it appears this flag is only used on the snapshot command, not true?

https://www.elastic.co/guide/en/elasticsearch/client/curator/current/repository.html

**Comment by abo-adapt** [comment]
Not entirely correct. It is used for anything to do with snapshots. That means the following commands: delete, show and snapshot. Delete can be told to delete either snapshots or indices, and show can be told to show either snapshots or indices. Snapshot makes a snapshot. My patch fixes the job definition for the delete command only. A better more general solution can probably be found.

**Comment by jlambert121** [comment]
Thanks for the response, let me know if #46 looks good.

**Comment by abo-adapt** [comment]
My ruby isn't perfect, but it seems to me, that it hardcodes --repository to be 'old' in curator_job_spec.rb. Am I just reading it wrong?

**Comment by jlambert121** [comment]
I think the only place old is is in the test.

**Comment by abo-adapt** [comment]
You are absolutely correct. My bad. It looks great. Looking forward to seeing a release with it :)
