### ISSUE TITLE
cron job has "Array(@exclude).map..."

### ISSUE THREAD

**Issue by magic69** [evenup/evenup-curator#44]
This puppet config:

    curator::job { 'delete_old_indices':
    command     => 'delete',
    master_only => true,
    older_than  => 90,
    cron_hour   => 7,
    cron_minute => 02,
    bin_file    => '/usr/bin/curator',
    exclude     => ['.kibana',],
    prefix      => 'xxxx',
    time_unit   => 'days',
    }

Generates this cron job:
`2 7 * * * /usr/bin/curator --master-only --host localhost --port 9200 --logfile /var/log/curator.log --loglevel INFO --logformat default delete indices --prefix 'xxxx' --time-unit days Array(@exclude).map { |element| "--exclude #{element}" }.join(' ') --older-than 90 --timestring '%Y.%m.%d'`

which is not working due to this:
`--time-unit days Array(@exclude).map { |element| "--exclude #{element}" }.join(' ')`

Any ideas ?

**Comment by SteveDevOps** [comment]
Just a thought -- check main cron log and see if any of it is getting truncated when it actually executes

**Comment by jlambert121** [comment]
2.1.1 released with this fix
