### ISSUE TITLE
curator jobs can be removed from within curator::job 

### ISSUE THREAD

**Issue by butangero** [evenup/evenup-curator#54]
Currently if you have a curator job specified that you no longer need there's no way to remove it. Please add the capability to remove jobs once they're no longer needed.

You may be able to wrap the stanza where the cron is defined in order to accomplish this.

**Comment by jlambert121** [comment]
It would be great to have this functionality, but unfortunately I don't have time to add it in the near future.  You could add an ensure => absent to the cron and then just set it to absent and it would go away as another option.  PR's are greatly appreciated!
