### ISSUE TITLE
bloom command is missing

### ISSUE THREAD

**Issue by bobak** [evenup/evenup-curator#55]
The `bloom` command is missing in the switch. You have it documented in the `default` case in line 234  though ;-)

**Comment by jlambert121** [comment]
Funny - it was there before the rewrite.  I'd be happy to merge a PR with it, but I don't have time to do it right now.

**Comment by bilsch** [comment]
@jlambert121 I wonder if the bloom filter subcommand even makes sense?https://www.elastic.co/guide/en/elasticsearch/client/curator/current/bloom.html

> It can sometime make sense to disable bloom filters. For instance, if you are logging into an index per day, and you have thousands of indices, the bloom filters can take up a sizable amount of memory. For most queries you are only interested in recent indices, so you don’t mind CRUD operations on older indices taking slightly longer.
> In these cases you can disable loading of the bloom filter on a per-index basis by updating the index settings

**Comment by jlambert121** [comment]
The module used to support the bloom command (hence the legacy documentation), but I removed it when I rewrote it because I didn't think it added any value (at least to me).

**Comment by bobak** [comment]
Agreed, the bloom command doesn't make much sense anymore and should be removed (as you've done in #58 ).
