### ISSUE TITLE
possible problem with default timestring value

### ISSUE THREAD

**Issue by bilsch** [evenup/evenup-curator#56]
Getting odd behavior with the escaping. I think its un-necessary

```
/usr/bin/curator --logfile /var/log/curator.log --loglevel INFO --logformat default --host f1-bschwanitz.dev.cmmint.net --port 9200 snapshot --repository eslog_backups indices --prefix 'logstash-' --time-unit hours --older-than 1 --timestring '\%Y.\%m.\%d'
No indices matched provided args.
```

```
/usr/bin/curator --logfile /var/log/curator.log --loglevel INFO --logformat default --host f1-bschwanitz.dev.cmmint.net --port 9200 snapshot --repository eslog_backups indices --prefix 'logstash-' --time-unit hours --older-than 1 --timestring '%Y.%m.%d'
```

https://github.com/evenup/evenup-curator/blob/master/manifests/job.pp#L29

Happy to submit a pull request to change but not sure if this is somehow an issue in my test vm

**Comment by jlambert121** [comment]
Is this off of master or the latest release?

**Comment by pnebert** [comment]
got the same problem, with these backslashes indices will not be found

**Comment by pnebert** [comment]
well, seems like in crontabs you have to escape the % sign cause it gets interpreted as newline, so for me the issue is solved

**Comment by pabrahamsson** [comment]
Tested and verified what @pnebert said above. I think this is a non-issue and can be closed.

**Comment by jlambert121** [comment]
Thanks
